server:
  port: 9001
  servlet:
    context-path: /admin

admin:
  service:
    keycloak:
      address: http://localhost:8080
      client-id: tej-local-client-1
      realm-name: tej-local-realm
      client-secret: QtpKGsCJDIpyVmLi8QZz7kUdSim3YiSW

spring:
  application:
    name: admin-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${admin.service.keycloak.address}/realms/${admin.service.keycloak.realm-name}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:8761/eureka/

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: ERROR
  net:
    guides: DEBUG



