server:
  port: 9001
  servlet:
    context-path: /admin



spring:
  application:
    name: admin-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tej-local-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka:
  hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.hostname}:8761/eureka/

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: ERROR
  net:
    guides: DEBUG

admin:
  service:
    client-id: tej-local-client-1
